### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FiePaw** [superbobby2000/VanishV2#53] opened 2021-10-31 03:52 UTC
PocketMine-MP Crash Dump Sat Oct 30 22:48:28 CDT 2021

Error: Player is not in the same world
File: pmsrc/src/pocketmine/entity/Entity
Line: 1954
Type: InvalidArgumentException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: VanishV2 v2.7

when player using /vanish or /v that make a crash

**Comment by Sulfuritium** [comment] 2021-10-31 17:42
same

**Comment by superbobby2000** [comment] 2021-10-31 18:21
I can't reproduce the issue, I need more info such as the full steps for it to happen and what plugins are loaded on your server

**Comment by Sulfuritium** [comment] 2021-11-01 08:55
Here is more information ^^

https://crash.pmmp.io/view/5394937

**Comment by Sulfuritium** [comment] 2021-11-02 08:16
It's when you connect in vanish mode or when you remove your vanish

**Comment by superbobby2000** [comment] 2021-11-03 22:36
this was an issue from PM which has been resolved in the new version (3.25.2)

**Closed by superbobby2000** 2021-11-03 22:36 UTC
Labels: cannot reproduce
